[project]
name = "mikrotik-inspector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.4.2",
    "fabric>=3.2.3",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
mikrotik-inspector = "mikrotik_inspector.__main__:cli"
mikrotik-dhcp-leases = "mikrotik_inspector.dhcp_leases:cli"

[dependency-groups]
dev = ["coveralls>=4.0.2", "mypy>=1.18.2", "pytest>=9.0.3", "ruff>=0.14.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
